site_name: spt
site_description: Scientific matplotlib plot rcParams configuration template python package.
copyright: Copyright &copy 2023-2023


theme:
  name: material
  language: zh
  icon: 
    logo: material/notebook-outline
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
  # palette:
  # - scheme: default
  # reference: https://github.com/HobbitQia/notebook/blob/note1/mkdocs.yml
  palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)" 
      scheme: default  #配色方案：浅色模式
      # primary: brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      # accent: brown  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode


extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/Bit-Part-Young
    # - name: Home
    #   icon: fontawesome/solid/house-chimney
    #   link: https://seekanotherland.xyz/mkdocs-demo/


# Extensions
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true


# reference: https://github.com/TonyCrane/note/blob/master/mkdocs.yml
extra_css:
  - css/tasklist.css


plugins:
  - search
  - changelog
  - statistics:
      page_check_metadata: 
  - mkdocs-jupyter
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - glightbox:
      width: 80%


nav:
  - Home: index.md
