[build-system]
requires = [
    "setuptools>=65.0.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "spt"
version = "0.2.3"
description = "Scientific matplotlib plot rcParams configuration template python package."
keywords = [
    "matplotlib",
]
authors = [
    {name = "yangsl", email = "3304839708@qq.com"},
]
maintainers = [
    {name = "yangsl", email = "3304839708@qq.com"},
]
dependencies = [
    "matplotlib>=3.7,<3.8",
    "numpy>=1.20.0",
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
]
readme = "README.md"

[project.optional-dependencies]
examples = [
    "pandas",
    "scikit-learn",
]

[project.urls]
Homepage = "https://github.com/Bit-Part-Young/spt"
documentation = "https://github.com/Bit-Part-Young/spt"
repository = "https://github.com/Bit-Part-Young/spt"

[tool.setuptools.packages.find]
include = ["spt"]
